import type { CardNewsDeck } from '../../types';

const deck: CardNewsDeck = {
  id: 'btc-riskoff-2026-06-13',
  project: 'alphalenz',
  title: { ko: '비트코인 위험회피 리포트', en: 'Bitcoin Risk-off Report' },
  source: 'https://alpha-lenz.com/ko/angle-reports/2026-06-13-alpha-lenz-bitcoin-report',
  date: '2026-06-13',
  slides: [
    { type: 'cover',
      eyebrow: { ko: 'AlphaLenz 앵글 리포트', en: 'AlphaLenz · Angle Report' },
      headline: { ko: '모두가 저점을 외칠 때\nAI는 달리 봤다', en: "Everyone said 'buy the dip.'\nAI disagreed." },
      tag: { ko: '비트코인 · 위험회피 · 2026.06.13', en: 'Bitcoin · Risk-off · 2026.06.13' } },
    { type: 'thesis',
      eyebrow: { ko: '핵심 결론', en: 'The verdict' },
      headline: { ko: "지금의 하락은\n'과잉 반응'이 아니다", en: "This selloff isn't\nan overreaction" },
      body: { ko: '시장은 과민반응이라 말하지만 데이터는 정반대다. 유동성 경색이 부른 구조적 하락 — 비트코인이 제 가격을 찾는 과정이다.',
              en: 'Markets call it panic; the data says otherwise. A structural decline driven by tightening liquidity — Bitcoin simply finding fair value.' } },
    { type: 'contrast',
      eyebrow: { ko: '시장의 해석 vs 실제', en: 'Narrative vs reality' },
      headline: { ko: '같은 하락, 정반대의 해석', en: 'Same drop, opposite reads' },
      left: { label: { ko: '시장의 시선', en: "The market's view" }, tone: 'down',
              text: { ko: "금리 인하 기대 후퇴와 AI 쏠림發 '캐리 청산' 우려", en: 'Fading rate-cut hopes and AI crowding spark carry-unwind fears' } },
      right: { label: { ko: '실제', en: 'The reality' }, tone: 'up',
               text: { ko: '소비심리 위축, 인플레이션 고착, 유동성 제약', en: 'Weak sentiment, sticky inflation, constrained liquidity' } } },
    { type: 'data',
      eyebrow: { ko: '데이터가 가리키는 것', en: 'What the data shows' },
      headline: { ko: '지난 한 달, 비트코인만\n홀로 무너졌다', en: 'In one month, only\nBitcoin collapsed' },
      chart: { kind: 'divergenceBar', rows: [
        { name: { ko: '비트코인', en: 'Bitcoin' }, value: '-17.06%', pct: 92, tone: 'down' },
        { name: { ko: '나스닥100', en: 'Nasdaq 100' }, value: '+0.19%', pct: 7, tone: 'up' },
      ] },
      note: { ko: "'디지털 금'도 'AI 자산'도 아니다. BTC–금 상관계수 0.044.", en: "Not 'digital gold,' not an 'AI asset.' BTC–gold correlation: 0.044." } },
    { type: 'context',
      eyebrow: { ko: '배경 · 거시 환경', en: 'Macro backdrop' },
      headline: { ko: '고금리 장기화가\n현실이 됐다', en: 'Higher-for-longer\nis now reality' },
      stats: [
        { label: { ko: '소비자심리 (UMCSENT)', en: 'Sentiment (UMCSENT)' }, value: '49.8', tone: 'down' },
        { label: { ko: '소비자물가 (CPI)', en: 'CPI' }, value: '334', tone: 'gold' },
        { label: { ko: '산업생산 (INDPRO)', en: 'Output (INDPRO)' }, value: '102.5', tone: 'neutral' },
      ],
      note: { ko: '위축된 소비 + 고착된 물가 = 스태그플레이션 신호.', en: 'Weak demand plus sticky prices — a stagflation signal.' } },
    { type: 'action',
      eyebrow: { ko: '권고 조치', en: 'Recommendation' },
      headline: { ko: '비트코인 축소,\n금으로 전환', en: 'Trim Bitcoin,\nrotate into gold' },
      chart: { kind: 'donut', segments: [
        { label: { ko: '비트코인 비중 ↓', en: 'Bitcoin ↓' }, weight: 30, tone: 'down' },
        { label: { ko: '금·안전자산 ↑', en: 'Gold & havens ↑' }, weight: 70, tone: 'gold' },
      ] },
      note: { ko: '구조적 약세 국면, 포트폴리오 방어가 우선이다.', en: 'In a structural downturn, defense comes first.' } },
    { type: 'list',
      eyebrow: { ko: '대안 자산 · 무효화 조건', en: 'Alternatives · Invalidation' },
      items: [
        { ko: '금 (XAU) — 스태그플레이션의 유일한 헤지', en: 'Gold (XAU) — the only stagflation hedge' },
        { ko: '달러 (USD) — 위험회피 심리의 수혜', en: 'US dollar — a risk-off beneficiary' },
        { ko: "단기국채 — '현금의 왕', 무위험 수익", en: "T-bills — 'cash is king,' risk-free yield" },
      ],
      note: { ko: '무효화 — T10Y2Y 마이너스 1주 이상 지속 시 시나리오 폐기.', en: 'Invalidation: if T10Y2Y inverts below zero for a week or more.' } },
    { type: 'cta',
      eyebrow: { ko: 'AlphaLenz', en: 'AlphaLenz' },
      headline: { ko: '남들보다 하루 먼저,\n시장의 진짜 신호를', en: 'The real market signal,\na day ahead' },
      body: { ko: '매일 축적되는 AI 앵글 리포트 — 결론부터 근거까지.', en: 'Daily AI angle reports — from verdict to evidence.' },
      url: 'alpha-lenz.com' },
  ],
};

export default deck;
