import type { CardNewsDeck } from '../../types';

const deck: CardNewsDeck = {
  id: 'btc-riskoff-2026-06-22',
  project: 'alphalenz',
  title: { ko: '비트코인 위험회피 리포트', en: 'Bitcoin Risk-off Report' },
  source: 'https://alpha-lenz.com/en/angle-reports/2026-06-22-alpha-lenz-bitcoin-report',
  date: '2026-06-22',
  slides: [
    { type: 'cover',
      eyebrow: { ko: 'AlphaLenz 앵글 리포트', en: 'AlphaLenz · Angle Report' },
      headline: { ko: '나스닥 +27%,\n비트코인은 −16%', en: 'Nasdaq +27%.\nBitcoin −16%.' },
      tag: { ko: '비트코인 · 위험회피 · 2026.06.22', en: 'Bitcoin · Risk-off · 2026.06.22' } },
    { type: 'thesis',
      eyebrow: { ko: '핵심 결론', en: 'The verdict' },
      headline: { ko: "$64K 지지선은\n'저점 매수'가 아니다", en: "$64K support isn't\n'buying the dip'" },
      body: { ko: "그건 '뒤늦은 매도'다. 디지털 금 서사가 무너진 지금, 비트코인은 안전자산이 아니라 가장 먼저 팔리는 위험자산이다.",
              en: "It's delayed selling. With the 'digital gold' story dead, Bitcoin is no longer a haven — it's the first risk asset to be dumped." } },
    { type: 'contrast',
      eyebrow: { ko: '시장의 해석 vs 실제', en: 'Narrative vs reality' },
      headline: { ko: '같은 하락, 정반대의 해석', en: 'Same drop, opposite reads' },
      left: { label: { ko: '시장의 시선', en: "The market's view" }, tone: 'down',
              text: { ko: 'AI 쏠림發 일시적 유동성 이탈 — 저가 매수 기회', en: 'A temporary liquidity drain from the AI boom — a dip to buy' } },
      right: { label: { ko: '실제', en: 'The reality' }, tone: 'up',
               text: { ko: '스태그플레이션 + 유동성 경색이 부른 구조적 하락', en: 'A structural decline driven by stagflation and a liquidity crunch' } } },
    { type: 'data',
      eyebrow: { ko: '데이터가 가리키는 것', en: 'What the data shows' },
      headline: { ko: '지난 3개월,\n−42%p 디커플링', en: '3 months,\n−42pp decoupling' },
      chart: { kind: 'divergenceBar', rows: [
        { name: { ko: '비트코인', en: 'Bitcoin' }, value: '-16.11%', pct: 59, tone: 'down' },
        { name: { ko: '나스닥100', en: 'Nasdaq 100' }, value: '+27.23%', pct: 100, tone: 'up' },
      ] },
      note: { ko: "BTC–나스닥 상관계수 0.0008. 더는 'AI 자산'도 '디지털 금'도 아니다.", en: "BTC–Nasdaq correlation: 0.0008. No longer an 'AI asset' — nor 'digital gold.'" } },
    { type: 'context',
      eyebrow: { ko: '배경 · 거시 환경', en: 'Macro backdrop' },
      headline: { ko: '스태그플레이션이\n현실이 됐다', en: 'Stagflation is\nnow reality' },
      stats: [
        { label: { ko: '소비자물가 (CPI)', en: 'CPI' }, value: '334', tone: 'gold' },
        { label: { ko: '소비자심리 (UMCSENT)', en: 'Sentiment (UMCSENT)' }, value: '49.8', tone: 'down' },
        { label: { ko: '장단기 금리차 (10Y-2Y)', en: '10Y-2Y spread' }, value: '0.27%', tone: 'neutral' },
      ],
      note: { ko: 'ETF 6주 연속 순유출 635억 달러 — 기관 수요의 구조적 후퇴.', en: '$63.5B in ETF outflows over six weeks — a structural retreat in institutional demand.' } },
    { type: 'action',
      eyebrow: { ko: '권고 조치', en: 'Recommendation' },
      headline: { ko: '비트코인 축소,\n금으로 전환', en: 'Trim Bitcoin,\nrotate into gold' },
      chart: { kind: 'donut', segments: [
        { label: { ko: '비트코인 비중 ↓', en: 'Bitcoin ↓' }, weight: 30, tone: 'down' },
        { label: { ko: '금·안전자산 ↑', en: 'Gold & havens ↑' }, weight: 70, tone: 'gold' },
      ] },
      note: { ko: '구조적 약세 국면 — 방어가 먼저다.', en: 'A structural downturn — defense comes first.' } },
    { type: 'list',
      eyebrow: { ko: '리스크 · 무효화 조건', en: 'Risks · Invalidation' },
      items: [
        { ko: 'CPI 335 돌파 시 위험자산 매도 가속', en: 'Selling accelerates if CPI tops 335' },
        { ko: '10Y-2Y 역전(−0.5%) 시 침체 신호', en: 'A 10Y-2Y inversion (−0.5%) flags recession' },
        { ko: 'ETF 순유출 지속 — 수요 공백 심화', en: 'Persistent ETF outflows deepen the demand gap' },
      ],
      note: { ko: '무효화 — BTC·나스닥 상관계수 0.2 위로 2주 + 반등 5%↑.', en: 'Invalidation: BTC–Nasdaq R² above 0.2 for two weeks and a 5%+ rebound.' } },
    { type: 'cta',
      eyebrow: { ko: 'AlphaLenz', en: 'AlphaLenz' },
      headline: { ko: '남들보다 하루 먼저,\n시장의 진짜 신호를', en: 'The real market signal,\na day ahead' },
      body: { ko: '매일 축적되는 AI 앵글 리포트 — 결론부터 근거까지.', en: 'Daily AI angle reports — from verdict to evidence.' },
      url: 'alpha-lenz.com' },
  ],
};

export default deck;
